baseurl: "/"
url: "http://www.vocabolangelo.org/"

exclude:
    - gradle*
    - settins.gradle.kts
    - build.gradle.kts
    - Gemfile
    - Procfile
    - README.md

plugins:
    - jekyll-rdf

letters: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

# Jekyll RDF settings
jekyll_rdf:
    path: "_data/vocabolangelo.ttl"
    default_template: "rdf/default"
    class_template_mappings:
        "http://www.w3.org/2004/02/skos/core#Concept": "rdf/concept"
        "http://xmlns.com/foaf/0.1/Person": "rdf/author"
        "http://www.vocabolangelo.org/Game" : "rdf/game"
