name: Releases

on:
  workflow_run:
    workflows: ["Validate RDF"]
    branches:
      - react
    types:
      - completed

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
